# Generated by Django 4.2.1 on 2023-10-27 05:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_netpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='netpost',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
